### ISSUE TITLE
Vulnerability of contentful-management dependency

### ISSUE THREAD

**Issue by hoirena** [watermarkchurch/contentful-schema-diff#133]
The project I'm working on currently has High vulnerability: "Server-Side Request Forgery" because of axios version 0.19.2 used in contentful-management 5.0.0-beta2.

contentful-management dependency has update to 7.3.1. and that version uses axios 0.21.1 which is not vulnerable.

**Comment by gburgett** [comment]
Thanks!  I'll look into upgrading the library
