### ISSUE TITLE
Default value for widgetNameSpace for changeFieldControl

### ISSUE THREAD

**Issue by akira90** [watermarkchurch/contentful-schema-diff#60]
I was wondering if a default value for widgetNameSpace can be applied instead of setting it to undefined?

I'm not sure on how this is done on contentful, when no custom field controls are applied to any fields - as far as I know it should be using the default value which is **builtIn**, however that is not being set.
_(checked the JSON preview in contentful - we have no fields with any custom field controls nor does it specify which field controls are being in use)_

Sometimes when the migration scripts are generated, they have the value of "built in" and sometimes "undefined" - hence why I suggested to place in the default value in case it does come to be undefined.

Currently the issue is when trying to transpile the typescript to javascript - it errors on _changeFieldControl_ when trying to pass _undefined_ to a param that expects either _'builtin' | 'extension'_.

**Comment by akira90** [comment]
Never mind - after careful consideration I think we may drop this tool, we are getting a lot of "undefined" values in the _widgetNameSpace_ and _widgetId_ fields, if we was to execute the migration script that was transpiled from typescript - we may end up breaking things in contentful.

**Comment by gburgett** [comment]
You're always welcome to submit a pull request!
