### ISSUE TITLE
Package causes ts linter to go crazy

### ISSUE THREAD

**Issue by arturhenryy** [watermarkchurch/contentful-schema-diff#95]
So i am experiencing this really odd behaviour with this package. First of all, it seems to work as expected BUT, having this package in my repository makes the typescript linter, after running it, fail almost every file and react component of the project and complaining about stuff that is not even there, like the usage of var in a file where only const is used e. g.
this only happens when this module is installed. when i remove it from my package.json, delete node_modules and make fresh install everything runs normal again and the linter does not find any issues.

    "tslint": "~5.20.1",
    "tslint-config-prettier": "~1.18.0",
    "typescript": "~3.7.3",

**Comment by gburgett** [comment]
It looks like I need to move tslint and typescript out of the package dependencies.  I'll do that for sure.
